baseurl             = "https://blog.ncu204.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "zh-CN"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Fly Thief"
title               = "Fly Thief"
pygmentsuseclasses  = true
# disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Code"
weight                 = -120
identifier             = "code"
url                    = "/posts/code"

[[menu.main]]
name                   = "Algorithm"
weight                 = -100
identifier             = "Algorithm"
url                    = "/posts/algorithm"

[[menu.main]]
name                   = "life"
weight                 = -90
identifier             = "life"
url                    = "/posts/life"

[[menu.main]]
name                   = "other"
weight                 = -90
identifier             = "other"
url                    = "/posts/other"

[[menu.main]]
name                   = "About"
weight                 = 100
identifier             = "about"
url                    = "/about/"


[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = true                         # whether to display small country flags for available translations
author                 = "Fly Thief"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Get Hungary"
email                  = "1449902124@qq.com"
extracssfiles          = []       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/favicon.ico"
github                 = "//github.com/flylzj"
# instagram              = "//instagram.com/you"
# px500                  = "//500px.com/username"
lang                   = "zh"
# linkedin               = "//linkedin.com/in/you"
noshowreadtime         = true                         # if true, don't show "<x> minutes read" in posts
selfintro              = "fly thief's blog"                            # appears in the site header when set to a non-empty string
#twitter                = "//twitter.com/you"
#mastodon               = "//example.com/@you"
#telegram               = "//t.me/you"

highlightjs            = true
# highlightjslanguages = ["go", "python"]                        # additional languages not included in the "common" set
highlightjsStyle     = "darcula"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

gitalk                 = false
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "your client id"
gitalk_clientSecret    = "your client secret"
gitalk_repo            = "your repo url"
gitalk_owner           = "the owner of this repo"
gitalk_admin           = ['a', 'list', 'of', 'administrator']

avatar                 = "img/lzj.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
