baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "zh-cn"
defaultContentLanguage  = "zh"
isMultilingual          = true
title                   = "fly thief"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-123141655-2"             # Tracking code, eg. "UA-111111111-1"
hasCJKLanguage           = true

[params]
    dateform            = "Mon Jan 2 2006 15:04:05"
    dateformfull        = "Mon Jan 2 2006 15:04:05 CCT"
    favicon             = "hugo.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "Call me Sam, a theme for Hugo."

# Metadata
    description         = " "            # Max 160 characters show in search results
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts/python"
    text = "Python"

[[params.mainMenu]]
    link = "/posts/golang"
    text = "Golang"

[[params.mainMenu]]
    link = "/posts/life"
    text = "MyLife"

[[params.mainMenu]]
    link = "/posts/other"
    text = "Other"

[[params.mainMenu]]
    link = "/about"
    text = "关于我"
