baseurl = "https://username.github.io"
DefaultContentLanguage = "zh-cn"
title = "flythief"
theme = "beautifulhugo"
metaDataFormat = "toml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = ""
  logo = "./lzj.jpg"
  favicon = "favicon.ico"
  dateFormat = "Mon Jan 2 2006 15:04:05"
  commit = false
  rss = true
  # comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  # socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "flylzj"
  website = "blog.ncu204.com"
  email = "1449902124@qq.com"
  github = "flylzj"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    parent = "blog"
    identifier = "python"
    name = "Python"
    url = "posts/python"
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "Golang"
    url = "posts/golang"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "algorithm"
    url = "posts/algorithm"
    weight = 3

[[menu.main]]
    parent = "blog"
    name = "other"
    url = "posts/other"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
